fixtures:
  repositories:
    common: git://github.com/evenup/evenup-common.git
    facter: git://github.com/evenup/evenup-facter.git
    logrotate: git://github.com/evenup/evenup-logrotate.git
    ruby: git://github.com/evenup/evenup-ruby.git
  symlinks:
    mcollective: "#{source_dir}"

